import React, { useState, useEffect, useCallback } from 'react'
import { fetchKPIs, fetchSegments, fetchChurn, fetchCLVDistribution, fetchActions, fetchCustomers } from '../../utils/api'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer, Cell, PieChart, Pie, Legend } from 'recharts'

// Standard A4 dimensions in px at 96 DPI: 794 x 1123
// We apply these via inline styles so html2canvas computes it perfectly regardless of the viewport
const PAGE_STYLE = {
  width: '794px',
  height: '1123px',
  background: '#0F172A', // Navy background from theme
  color: '#F1F5F9', // Primary text
  padding: '40px',
  boxSizing: 'border-box',
  fontFamily: 'Inter, sans-serif',
  position: 'relative',
  overflow: 'hidden',
  display: 'flex',
  flexDirection: 'column',
}

const CHURN_COLORS = { Low: '#10B981', Medium: '#F59E0B', High: '#EF4444' }
const PIE_COLORS = ['#22D3EE', '#A855F7', '#EC4899', '#10B981', '#F59E0B', '#3B82F6']
const SEGMENT_DESCRIPTIONS = {
  Platinum: 'Highest value loyalists. Focus on white-glove retention.',
  Gold: 'Consistent high-spenders. Target for premium upsells.',
  Silver: 'Average frequent buyers. Target with loyalty programs.',
  Bronze: 'Low engagement or single-purchasers. Require re-engagement.',
}

export default function CustomerReportTemplate({ filters }) {
  const [data, setData] = useState({
    kpis: null, segments: null, churn: null, clv: null, actions: null, topCustomers: [],
  })

  // Load everything needed for the report
  const loadData = useCallback(async () => {
    try {
      const [k, seg, c, clv, act, top] = await Promise.all([
        fetchKPIs(filters),
        fetchSegments(filters),
        fetchChurn(filters),
        fetchCLVDistribution(filters),
        fetchActions(filters),
        fetchCustomers({ ...filters, sortBy: 'clv', sortDir: 'desc', limit: 10 }),
      ])
      setData({
        kpis: k.data,
        segments: seg.data,
        churn: c.data,
        clv: clv.data,
        actions: act,
        topCustomers: top.data || [],
        timestamp: new Date().toLocaleString(),
      })
    } catch(e) {
      console.error(e)
    }
  }, [filters])

  // Initial load dependency
  useEffect(() => { loadData() }, [loadData])

  const { kpis, segments, churn, clv, actions, topCustomers, timestamp } = data

  const Footer = ({ page }) => (
    <div className="absolute bottom-6 left-10 right-10 flex justify-between text-[10px] text-slate-500 border-t border-slate-800 pt-3">
      <span>Generated by CustomerIQ Dashboard</span>
      <span>CONFIDENTIAL / INTERNAL USE ONLY</span>
      <span>Page {page}</span>
    </div>
  )

  const TitleHeader = ({ title }) => (
    <div className="mb-6 pb-2 border-b border-slate-700/50">
      <h2 className="text-xl font-bold text-cyan-400">{title}</h2>
    </div>
  )

  const fmt = (n) => n != null ? Number(n).toLocaleString() : '—'
  const fmtK = (n) => n != null ? `₹${(n / 1000).toFixed(1)}k` : '—'

  return (
    <div id="pdf-report-container" style={{ display: 'none' }}>
      
      {/* ───────────────────────────────────────────────────────────────── */}
      {/* PAGE 1: Cover & Executive Summary */}
      {/* ───────────────────────────────────────────────────────────────── */}
      <div className="pdf-page" style={PAGE_STYLE}>
        {/* Cover Header */}
        <div className="mt-12 mb-16 text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-xl bg-gradient-to-br from-cyan-400 to-purple-500 mb-6 shadow-glow-cyan">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 3v18h18"/><path d="m19 9-5 5-4-4-3 3"/></svg>
          </div>
          <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-400 tracking-tight">Customer Behavior Analytics Report</h1>
          <p className="text-lg text-slate-400 mt-4 font-medium tracking-wide border-t border-slate-800 pt-4 mx-auto max-w-md">Internal Intelligence Document</p>
          <div className="mt-6 inline-block bg-slate-800/50 rounded-lg px-4 py-2 border border-slate-700">
            <p className="text-xs text-slate-300">Generated: {timestamp}</p>
          </div>
        </div>

        <TitleHeader title="Executive Summary" />
        
        <div className="grid grid-cols-2 gap-6 mb-8">
          <div className="bg-slate-800/40 border border-slate-700 p-5 rounded-xl">
            <p className="text-xs text-slate-400 uppercase tracking-widest mb-1">Total Customers Analyzed</p>
            <p className="text-4xl font-bold text-white">{fmt(kpis?.totalCustomers)}</p>
          </div>
          <div className="bg-slate-800/40 border border-slate-700 p-5 rounded-xl">
            <p className="text-xs text-slate-400 uppercase tracking-widest mb-1">Average Customer LTV</p>
            <p className="text-4xl font-bold text-purple-400">{fmtK(kpis?.avgCLV)}</p>
          </div>
          <div className="bg-slate-800/40 border border-slate-700 p-5 rounded-xl">
            <p className="text-xs text-slate-400 uppercase tracking-widest mb-1">Total Period Revenue</p>
            <p className="text-4xl font-bold text-emerald-400">₹{kpis?.totalRevenue ? (kpis.totalRevenue / 1e6).toFixed(2) : '—'}M</p>
          </div>
          <div className="bg-slate-800/40 border border-slate-700 p-5 rounded-xl">
            <p className="text-xs text-slate-400 uppercase tracking-widest mb-1">High-Value Segment</p>
            <p className="text-4xl font-bold text-cyan-400">{fmt(kpis?.highValueCount)} <span className="text-sm font-normal text-slate-400 ml-1">users</span></p>
          </div>
          <div className="bg-rose-900/20 border border-rose-900/50 p-5 rounded-xl col-span-2 flex items-center justify-between">
            <div>
              <p className="text-xs text-rose-300/80 uppercase tracking-widest mb-1">At-Risk Customers (High Churn)</p>
              <p className="text-4xl font-bold text-rose-400">{fmt(kpis?.highChurn)}</p>
            </div>
            <div className="text-right">
              <p className="text-3xl font-bold text-rose-400">{kpis?.churnPercent}%</p>
              <p className="text-xs text-rose-300">Overall risk pool</p>
            </div>
          </div>
        </div>

        <div className="bg-slate-800/30 p-5 rounded-xl border border-slate-700 text-sm text-slate-300 leading-relaxed flex-1">
          <p className="mb-2"><strong className="text-white">Analysis Overview:</strong> This document represents a snapshot of global customer engagement over the current tracking period. The metrics are generated using our internal RFM (Recency, Frequency, Monetary) scaling model mapped directly against lifetime value predictive arrays.</p>
          <p>Of the targeted userbase, we are noticing a <strong>{kpis?.churnPercent}% high-risk churn rate</strong> alongside an average engagement rating of <strong>{kpis?.avgEngagement} / 15</strong>. Strategic focus should shift immediately towards the actionable matrix outlined on Page 3.</p>
        </div>

        <Footer page={1} />
      </div>

      {/* ───────────────────────────────────────────────────────────────── */}
      {/* PAGE 2: Segmentation & Churn Analysis */}
      {/* ───────────────────────────────────────────────────────────────── */}
      <div className="pdf-page" style={PAGE_STYLE}>
        <TitleHeader title="Customer Segmentation" />
        
        <table className="w-full text-left text-sm mb-10 border-collapse">
          <thead>
            <tr className="border-b border-slate-700">
              <th className="py-3 font-semibold text-slate-400 w-1/4">Segment Cluster</th>
              <th className="py-3 font-semibold text-slate-400 w-1/6">User Count</th>
              <th className="py-3 font-semibold text-slate-400 w-1/6">Percentage</th>
              <th className="py-3 font-semibold text-slate-400">Behavioral Description</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800">
            {(segments || []).sort((a,b) => b.count - a.count).map(s => (
              <tr key={s.name}>
                <td className="py-4 font-bold text-white">{s.name}</td>
                <td className="py-4 text-slate-300">{s.count}</td>
                <td className="py-4 text-cyan-400">{((s.count / kpis?.totalCustomers) * 100).toFixed(1)}%</td>
                <td className="py-4 text-slate-400 text-xs pr-4">{SEGMENT_DESCRIPTIONS[s.name] || 'General user segment.'}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <TitleHeader title="Churn Risk Analysis" />

        <div className="flex gap-6 mb-6">
          <div className="flex-1 bg-slate-800/40 p-5 rounded-xl border border-slate-700 h-64">
             <ResponsiveContainer width="100%" height="100%">
              <BarChart data={churn || []} barSize={40}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                <XAxis dataKey="name" stroke="#94A3B8" fontSize={11} tickLine={false} axisLine={false} />
                <YAxis stroke="#94A3B8" fontSize={11} tickLine={false} axisLine={false} />
                <Bar dataKey="count" radius={[4,4,0,0]}>
                  {(churn || []).map((entry) => (
                    <Cell key={entry.name} fill={CHURN_COLORS[entry.name] || '#6366F1'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
          
          <div className="w-1/3 flex flex-col gap-3">
             {(churn || []).map(d => (
               <div key={d.name} className="bg-slate-800/40 p-4 rounded-xl border border-slate-700 flex-1 flex flex-col justify-center">
                 <p className="text-xs font-semibold uppercase mb-1" style={{color: CHURN_COLORS[d.name]}}>{d.name} Risk</p>
                 <p className="text-2xl font-bold text-white">{d.count} <span className="text-xs text-slate-400 font-normal ml-1">users</span></p>
                 <p className="text-xs text-slate-400 mt-1">{((d.count / kpis?.totalCustomers) * 100).toFixed(1)}% of base</p>
               </div>
             ))}
          </div>
        </div>

        <div className="bg-rose-900/10 p-4 rounded-xl border border-rose-900/30 text-sm text-slate-300">
           <strong className="text-rose-400">Risk Assessment:</strong> Users falling into the High Risk category exhibit dropped app login frequencies over the 30-day trailing window and severe cart abandonment metrics. Immediate mitigation campaigns required.
        </div>

        <Footer page={2} />
      </div>

      {/* ───────────────────────────────────────────────────────────────── */}
      {/* PAGE 3: CLV & Action Recommendations */}
      {/* ───────────────────────────────────────────────────────────────── */}
      <div className="pdf-page" style={PAGE_STYLE}>
        <TitleHeader title="Customer Lifetime Value (CLV)" />
        
        <div className="flex gap-6 mb-8 h-48">
          <div className="flex-1 bg-slate-800/40 p-2 rounded-xl border border-slate-700">
             <ResponsiveContainer width="100%" height="100%">
               <PieChart>
                 <Pie data={clv || []} cx="50%" cy="50%" innerRadius={40} outerRadius={70} dataKey="count" paddingAngle={2}>
                   {(clv || []).map((_, i) => <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />)}
                 </Pie>
                 <Legend layout="vertical" verticalAlign="middle" align="right" wrapperStyle={{fontSize: '10px', color: '#cbd5e1'}} />
               </PieChart>
             </ResponsiveContainer>
          </div>
          <div className="flex-1 flex flex-col justify-center bg-slate-800/40 p-5 rounded-xl border border-slate-700">
            <p className="text-sm font-semibold text-white mb-2">CLV Distribution Summary</p>
            <p className="text-xs text-slate-400 leading-relaxed">
              The aggregate lifetime value is dispersed into granular buckets. A heavily top-skewed curve indicates excellent retention within the core Platinum user-bracket. Focus on moving the highest volume mid-tier bubble forward.
            </p>
          </div>
        </div>

        <TitleHeader title="Top 10 Customers (CLV Ranking)" />
        <table className="w-full text-left text-xs mb-8 border-collapse">
          <thead>
            <tr className="border-b border-slate-700">
              <th className="py-2 font-semibold text-slate-400">Customer ID</th>
              <th className="py-2 font-semibold text-slate-400">Segment</th>
              <th className="py-2 font-semibold text-slate-400">Total Spend</th>
              <th className="py-2 font-semibold text-slate-400">Orders</th>
              <th className="py-2 font-semibold text-slate-400 text-right">Ext. CLV</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/50">
            {(topCustomers || []).map(c => (
              <tr key={c.customerID}>
                <td className="py-2 font-mono text-cyan-400">{c.customerID}</td>
                <td className="py-2 text-slate-300">{c.segmentLabel}</td>
                <td className="py-2 text-slate-300">₹{c.totalSpend?.toLocaleString()}</td>
                <td className="py-2 text-slate-300">{c.totalOrders}</td>
                <td className="py-2 text-purple-400 font-bold text-right">₹{c.clv?.toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <TitleHeader title="Business Action Matrix" />
        <div className="grid grid-cols-2 gap-4">
          {(actions?.data || []).sort((a,b) => b.count - a.count).map((act, i) => (
             <div key={act.action} className="bg-slate-800/50 p-4 rounded-xl border border-slate-700 flex justify-between items-center">
               <div className="flex items-center gap-3">
                 <div className="w-3 h-3 rounded-full" style={{background: PIE_COLORS[i % PIE_COLORS.length]}} />
                 <span className="font-semibold text-sm text-slate-100">{act.action}</span>
               </div>
               <span className="text-lg font-bold text-white">{act.count}</span>
             </div>
          ))}
        </div>

        <Footer page={3} />
      </div>

    </div>
  )
}
